name: Compilar Web Boda

on:
  push:
    branches: [ "main" ] # O la rama principal que utilices

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar repositorio
      uses: actions/checkout@v4

    - name: ⚙️ Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: 📦 Instalar dependencias
      run: npm install

    - name: 🛠️ Compilar proyecto (Build)
      run: npm run build

    - name: ✅ Verificación de compilación exitosa
      run: echo "¡La compilación de la página de la boda finalizó con éxito!"
